// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1388.commands;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc1388.Robot;
import org.usfirst.frc1388.RobotMap;

/**
 *
 */
public class AutonomousTurn extends Command {
	private boolean isTime;
	
	private double power;
	
	private double angle;
	private int time;
	
	private double error;
	private final double p = 0.1;
	private final double maxTurnPwr = 0.2; // not tested
	private final double marginOfErrorUp = 0.3; // not tested
	private final double marginOfErrorDwn = -0.3; // not tested
	
	private Timer timer;

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public AutonomousTurn(double angle) {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.driveTrain);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        isTime = false;
        this.angle = angle;
        error = angle - Robot.gyro.getAngle();
    }
    
    public AutonomousTurn(int time) {
    	isTime = true;
    	this.time = time;
    	
    	requires(Robot.driveTrain);
    	
    	timer = new Timer();
    	timer.reset();
    	
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
    	if(isTime == true) {
    		timer.start();
    	}else {
    		Robot.gyro.reset();    		
    	}
    	System.out.println("AutonomousTurn init");
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
    	if( this.isTime == true) {
    		if( this.time != timer.get()) {
    			power = 1;
        		RobotMap.driveTrainmecanumDrive.driveCartesian(0, 0, power, 0);
        		// check current time, if not at setpoint, continue move forward
    		}    		
    	} else {
    		if(error > marginOfErrorUp || error < marginOfErrorDwn ) {
    			//power = p * error; dont want because it might overshoot/undershoot indefinitely and/or for too long. 
    			power = maxTurnPwr;
    			RobotMap.driveTrainmecanumDrive.driveCartesian(0, 0, power, 0);
    		}
    		
    		// check current gyroVal, if not = dist, move
    		
    	}
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
    	// if this.time == timer return true
    	if(this.isTime == true) {
    		if( this.time == timer.get()) {
        		timer.stop();
        		return true;  	
    	}else {
    		if(error < marginOfErrorUp && error > marginOfErrorDwn) {
    			return true;
    		}
    	}
    	
    	}
    	return true;
    }
    // Called once after isFinished returns true
    @Override
    protected void end() {
    	
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
    }
}
