// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1388.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc1388.Robot;
import org.usfirst.frc1388.RobotMap;

/**
 *
 */
public class AutonomousDrive extends Command {
	
	private static double p = 0;
	private static double threshold = .5;
	
	private double error;
	
	private double power;

	private boolean isTime;

	
	private double distance;
	private int time;
	
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public AutonomousDrive(double distance) {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.driveTrain);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        
        isTime = false;
        this.distance = distance;
    }
    
    public AutonomousDrive(int time) {
    	
    	requires(Robot.driveTrain);
    	
    	isTime = true;
    	this.time = time;
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
    	// if time true, start timer
    	System.out.println("AutonomousDrive init");
    	RobotMap.driveTrainleftEncoder.reset();
    	RobotMap.driveTrainrightEncoder.reset();
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
    	
    	if( this.isTime == true) {
    		//if( this.time != ( )
    			//power = .7;
    			//RobotMap.driveTrainmecanumDrive.driveCartesian(power, 0, 0, 0);
    	} else {
    		error = distance - ((RobotMap.driveTrainleftEncoder.getDistance() + RobotMap.driveTrainrightEncoder.getDistance())/2);
    		power = p * error;
    		power /= 2;
    		if(Math.abs(power) <= .2){
    			power = 0;
    		}
    		RobotMap.driveTrainmecanumDrive.driveCartesian(power, 0, 0, 0);
    	}
    	
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
    	// if this.time == timer return true
    	if(this.isTime == true) {
    		if(this.time == RobotMap.driveTrainleftEncoder.get()) {
        		return true;
    		}
    	}else {
    		if( Math.abs(this.error) < threshold) {
    			return true;
    		}
    	}
    	// if this.distnace - encDistance = 0, return true
       return true;
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
    }
}
