// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1388.commands;
import edu.wpi.first.wpilibj.GenericHID.Hand;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc1388.Robot;
import org.usfirst.frc1388.RobotMap;

/**
 *
 */
public class Drive extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public Drive() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.driveTrain);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
    	
    	// set deadband. Xbox Controller seems to need at least 0.1
    	RobotMap.driveTrainmecanumDrive.setDeadband(0.2);
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
    	
    	double leftStickY = Robot.oi.getDriveController().getY(Hand.kLeft);
    	double leftStickX = Robot.oi.getDriveController().getX(Hand.kLeft);
    	double rightStickX = Robot.oi.getDriveController().getX(Hand.kRight);
    	
    	// get Gyro Z angle and adjust so is always between 0 and 360
    	double gyroZ = Robot.gyro.getAngleZ();
    	//if (gyroZ > 360) gyroZ-=360;
    	//if (gyroZ < 0) gyroZ+=360;
    	    	
    	// reverse left stick X
    	leftStickY = -leftStickY;
    	System.out.println("LeftStickX: " + leftStickX + "\tLeftStickY: " + leftStickY + "\t rightStickX: " + rightStickX);
    	
    	
    	// reverse right stick X
    	//rightStickX = -rightStickX;
    	
    	System.out.println(gyroZ);
    	
    	RobotMap.driveTrainmecanumDrive.driveCartesian(leftStickX, leftStickY, rightStickX, -gyroZ);
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
    }
}
