// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1388.commands;
import edu.wpi.first.wpilibj.GenericHID.Hand;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc1388.Robot;
import org.usfirst.frc1388.UsbLogging;
import org.usfirst.frc1388.subsystems.Elevator;

/**
 *
 */
public class MoveElevator extends Command {

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

	//private final Elevator elevator = Robot.elevator;
	private final double k_elevatorDeadband = 0.1; // deadband for the elevator, not tested
	
	private final Elevator elevator = Robot.elevator;

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
	public MoveElevator() {

		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.elevator);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	}

	// Called just before this Command runs the first time
	@Override
	protected void initialize() {
    	UsbLogging.printLog(">>> " + this.getClass().getSimpleName() + " started");
	}

	// Called repeatedly when this Command is scheduled to run
	@Override
	protected void execute() {

		// TODO make on/off vs hold
		boolean override = Robot.oi.getOpController().getBackButton();

		double leftTrigger = Robot.oi.getOpController().getTriggerAxis(Hand.kLeft);

		double rightTrigger = Robot.oi.getOpController().getTriggerAxis(Hand.kRight);

		double elevatorSpeed = 0;

		if ( rightTrigger > 0 && leftTrigger > 0)  { // If both triggers pressed, elevatorSpeed = 0

			elevatorSpeed = 0;

		} else if (rightTrigger > 0) {
			
			elevatorSpeed = applyDeadband(rightTrigger, k_elevatorDeadband);
			
		} else if (leftTrigger > 0) {
			
			elevatorSpeed = -applyDeadband(leftTrigger, k_elevatorDeadband); // negative because trigger joysticks both postive range
			
		}

		elevator.setMotor(elevatorSpeed, override);
	}

	// Make this return true when this Command no longer needs to run execute()
	@Override
	protected boolean isFinished() {
		return false;
	}

	// Called once after isFinished returns true
	@Override
	protected void end() {
		elevator.setMotor(0, false);
    	UsbLogging.printLog("<<< " + this.getClass().getSimpleName() + " ended");
	}

	// Called when another command which requires one or more of the same
	// subsystems is scheduled to run
	@Override
	protected void interrupted() {
    	UsbLogging.printLog("<<< " + this.getClass().getSimpleName() + " interrupted");
		end();
	}

	private double applyDeadband(double value, double deadband) {
		if (Math.abs(value) > deadband) {
			if (value > 0.0) {
				return (value - deadband) / (1.0 - deadband);
			} else {
				return (value + deadband) / (1.0 - deadband);
			}
		} else {
			return 0.0;
		}
	}
}
