// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1388;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import com.mindsensors.CANSD540;

import edu.wpi.first.wpilibj.drive.MecanumDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static WPI_TalonSRX driveTrainrightFront;
    public static WPI_TalonSRX driveTrainrightRear;
    public static WPI_TalonSRX driveTrainleftFront;
    public static WPI_TalonSRX driveTrainLeftRear;
    public static MecanumDrive driveTrainMecanumDrive1;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    public static CANSD540 leftForkMotor;
    public static CANSD540 rightForkMotor;
    
    public static CANSD540 elevatorMotor;
    
    public static CANSD540 armMotor;

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainrightFront = new WPI_TalonSRX(2);
        
        
        driveTrainrightRear = new WPI_TalonSRX(1);
        
        
        driveTrainleftFront = new WPI_TalonSRX(3);
        
        
        driveTrainLeftRear = new WPI_TalonSRX(4);
        
        
        driveTrainMecanumDrive1 = new MecanumDrive(driveTrainleftFront, driveTrainLeftRear,
              driveTrainrightRear, driveTrainrightFront);
        LiveWindow.addActuator("DriveTrain", "Mecanum Drive 1", driveTrainMecanumDrive1);
        driveTrainMecanumDrive1.setSafetyEnabled(true);
        driveTrainMecanumDrive1.setExpiration(0.1);
        driveTrainMecanumDrive1.setMaxOutput(1.0);


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS\
        leftForkMotor =  new CANSD540(8);
        rightForkMotor = new CANSD540(8);
        
        elevatorMotor = new CANSD540(8);
        
        armMotor = new CANSD540(8);
    }
}
