// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1388;

import com.mindsensors.CANSD540;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;
import edu.wpi.first.wpilibj.Victor;
import edu.wpi.first.wpilibj.drive.MecanumDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveTrainrightFront;
    public static SpeedController driveTrainrigthRear;
    public static SpeedController driveTrainleftFront;
    public static SpeedController driveTrainleftRear;
    public static MecanumDrive driveTrainmecanumDrive;
    public static SpeedController elevatorelevatorMotor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CANSD540 forksleftForkMotor;
    public static CANSD540 forksrightForkMotor;

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainrightFront = new Victor(1);
        LiveWindow.addActuator("DriveTrain", "rightFront", (Victor) driveTrainrightFront);
        driveTrainrightFront.setInverted(false);
        driveTrainrigthRear = new Victor(0);
        LiveWindow.addActuator("DriveTrain", "rigthRear", (Victor) driveTrainrigthRear);
        driveTrainrigthRear.setInverted(false);
        driveTrainleftFront = new Victor(2);
        LiveWindow.addActuator("DriveTrain", "leftFront", (Victor) driveTrainleftFront);
        driveTrainleftFront.setInverted(false);
        driveTrainleftRear = new Victor(3);
        LiveWindow.addActuator("DriveTrain", "leftRear", (Victor) driveTrainleftRear);
        driveTrainleftRear.setInverted(false);
        driveTrainmecanumDrive = new MecanumDrive(driveTrainleftFront, driveTrainleftRear,
              driveTrainrightFront, driveTrainrigthRear);
        LiveWindow.addActuator("DriveTrain", "mecanumDrive", driveTrainmecanumDrive);
        driveTrainmecanumDrive.setSafetyEnabled(true);
        driveTrainmecanumDrive.setExpiration(0.1);
        driveTrainmecanumDrive.setMaxOutput(1.0);

        elevatorelevatorMotor = new Talon(4);
        LiveWindow.addActuator("Elevator", "elevatorMotor", (Talon) elevatorelevatorMotor);
        elevatorelevatorMotor.setInverted(false);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        
        
    }
}
